FROM debian:bookworm-slim

# Environment Variables
ENV GODOT_VERSION "4.3"
ENV GODOT_VERSION_FULL "4.3-beta2"
ENV GODOT_GAME_NAME "chathunt" # Name of the PCK file you want to run on the server
ENV HTTPS_GIT_REPO ""
ENV BUILT_DIR ""

# Updates and installs
RUN apt-get update
#RUN apt add --no-cache bash
RUN apt-get install -y wget unzip
#RUN apt add --no-cache git

# Allow this to run Godot
#RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.31-r0/glibc-2.31-r0.apk
#RUN apk add --allow-untrusted glibc-2.31-r0.apk

# Download Godot, version is set from environment variables
RUN wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/beta2/Godot_v${GODOT_VERSION_FULL}_linux.x86_64.zip \
    && mkdir ~/.cache \
    && mkdir -p ~/.config/godot \
    && unzip Godot_v${GODOT_VERSION_FULL}_linux.x86_64.zip \
    && mv Godot_v${GODOT_VERSION_FULL}_linux.x86_64 /usr/local/bin/godot \
    && rm -f Godot_v${GODOT_VERSION_FULL}_linux.x86_64.zip

# Make directory to run the app from and then run the app
RUN mkdir /godotapp
WORKDIR /godotapp
COPY . .
CMD ./ChatHunt.sh

#RUN git clone ${HTTPS_GIT_REPO} .
#CMD godot --main-pack ${GODOT_GAME_NAME}.pck
